version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000" # Map port 3000 of the container to port 3000 of the host
    env_file:
      - .env # Load environment variables from the .env file
